image: node:8-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

Build:
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    when: on_success
    paths:
      - dist/
    expire_in: 1 week
  only:
    - develop
  tags:
    - docker

Deploy:
  stage: deploy
  dependencies:
    - Build
  script:
    - apk add --update --no-cache sshpass
    - apk add --update --no-cache openssh sshpass
    - sshpass -v
    - cd dist/
    - export SSHPASS=$SSHPASS
    - sshpass -e scp -o stricthostkeychecking=no -P 53667 -r . wwwhostingperu@wwwhostingperu.com:/home/wwwhostingperu/www/vue

  only:
    - develop

  tags:
    - docker
